### ISSUE TITLE
Missing files in plugin for both Android and iOS

### ISSUE THREAD

**Issue by radariii** [mfpdev/mfp-live-update-cordova-plugin#1]
```
Failed to install 'cordova-plugin-mfp-liveupdate':CordovaError: Uh oh!
"/Users/crmiles/Documents/dev/workspaces/git/Community-Health-Demo/plugins/cordova-plugin-mfp-liveupdate/src/ios/API/Configuration.swift" not found!
    at copyFile (/Users/crmiles/Documents/dev/workspaces/git/Community-Health-Demo/platforms/ios/cordova/lib/plugman/pluginHandlers.js:274:36)
    at copyNewFile (/Users/crmiles/Documents/dev/workspaces/git/Community-Health-Demo/platforms/ios/cordova/lib/plugman/pluginHandlers.js:306:5)
    at installHelper (/Users/crmiles/Documents/dev/workspaces/git/Community-Health-Demo/platforms/ios/cordova/lib/plugman/pluginHandlers.js:224:13)
    at handlers.source-file.install (/Users/crmiles/Documents/dev/workspaces/git/Community-Health-Demo/platforms/ios/cordova/lib/plugman/pluginHandlers.js:34:13)
    at Object.ActionStack.process (/Users/crmiles/Documents/dev/workspaces/git/Community-Health-Demo/platforms/ios/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/crmiles/Documents/dev/workspaces/git/Community-Health-Demo/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/crmiles/Documents/dev/workspaces/git/Community-Health-Demo/platforms/ios/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/Users/crmiles/Documents/dev/workspaces/git/Community-Health-Demo/platforms/ios/cordova/Api.js:219:10)
    at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:611:6)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:407:28
Error: Uh oh!
"/Users/crmiles/Documents/dev/workspaces/git/Community-Health-Demo/plugins/cordova-plugin-mfp-liveupdate/src/ios/API/Configuration.swift" not found!
```

**Comment by IdanAdar** [comment]
This error seems to occur if adding the plugin **after** a platform was added.
If I add the plugin **before** a platform is added, the installation passes, but when then adding an environment, it fails again.

**Comment by taitelman** [comment]
will look at it  . I identified the issue. meanwhile I will document it into the readme file
and tell users to keep platform+plugin install order.

**Comment by taitelman** [comment]
fixed.

**Comment by taitelman** [comment]
still found some scenario with errors. re-opening.

**Comment by taitelman** [comment]
plugin.xml specifies hook script but these are not called when running 
`cordova plugin add http://github.com/mfpdev/mfp-live-update-cordova-plugin`
not sure why as it works when using local repo (using `cordova plugin add --save localFolder`)
current error is:
`error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-mfp-liveupdate':CordovaError: Uh oh!
"/samples/MyApp/plugins/cordova-plugin-mfp-liveupdate/src/ios/API/Configuration.swift" not found!
`

**Comment by taitelman** [comment]
it now copy the relevant files but ! still report an error. however, if `cordova build` command is re-run : all is ok

**Comment by taitelman** [comment]
added a 5 sec sleep and now it is resolved.
